DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS tags;

CREATE TABLE tags (
  id SERIAL4 PRIMARY KEY,
  category VARCHAR(255) UNIQUE
);

CREATE TABLE transactions (
  id SERIAL4 PRIMARY KEY,
  item VARCHAR(255),
  value NUMERIC NOT NULL CHECK (value > 0),
  merchant VARCHAR(255),
  tag_id INT4 REFERENCES tags(id) ON DELETE CASCADE
);